### ISSUE TITLE
have a problem with run on android studio

### ISSUE THREAD

**Issue by kingdoom0** [sarwan-singh/Ardberry-E-Magazine#1]
have this problem when I import it into android studio

Build file 'C:\Users\zking\Downloads\Ardberry-E-Magazine-master\app\build.gradle' line: 1

A problem occurred evaluating root project 'app'.
> Plugin with id 'com.android.application' not found.

**Comment by sarwan-singh** [comment]
@kingdoom0 The app doesn't contain all files in it. So you cannot directly just import the app into android studio. To avoid the privacy issues of the company app, the uploaded app has many files missing. But if you want to have this project for your use, just create a new project, then use the dependencies in build.gradle file and then use the activities in your app manually.
